# ServiceAccount for Kibana
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kibana-logging
  namespace: dev
---
# Kibana Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logging
  namespace: dev
  labels:
    k8s-app: kibana-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logging
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      serviceAccountName: kibana-logging
      containers:
      - name: kibana-logging
        image: docker.elastic.co/kibana/kibana-oss:7.5.0
        resources:
          # Increased CPU and memory limits
          limits:
            cpu: 2000m         # 2 CPUs
            memory: 4Gi        # 4 GB memory
          requests:
            cpu: 1000m         # 1 CPU
            memory: 2Gi        # 2 GB memory
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch-logging:9200  # Ensure Kibana points to Elasticsearch service
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
---
# Kibana Service
apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: dev
  labels:
    k8s-app: kibana-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Kibana"
spec:
  type: NodePort  # NodePort for external access
  ports:
    - port: 5601
      protocol: TCP
      targetPort: ui
      name: ui
  selector:
    k8s-app: kibana-logging

